version: "3.1"
services:

 db:
   image: postgres:9.6.1
   environment:
     POSTGRES_PASSWORD: adminadmin
     POSTGRES_DB: IssueDB
   volumes:
     - postgres-data:/var/lib/postgresql/data

 issue-tracker-project:
   image: issue-tracker-project
   
   ports:
     - "8080:8080"
     - "4848:4848"
     - "8181:8181"

   volumes:
     - ./issue-tracker-project/deployments:/opt/payara41/deployments
volumes: 
  postgres-data:
    external: true